module.exports = {
    REGISTER: "REGISTER",
    NEW_USER: "NEW_USER",
    EXISTING_USER: "EXISTING_USER",
    GET_USER_DATA: "GET_USER_DATA",
    SET_USER_DATA: "SET_USER_DATA",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
    RESET: "RESET",
    LOGOUT: "LOGOUT",
    GET_TOKEN: "GET_TOKEN"
}